import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AuthModule } from 'src/auth';
import {
  BacklogItemController,
  IssueController,
  ProjectController,
  WorkspaceController,
  WorkspaceMemberInviteController,
} from './application/controllers';
import {
  AcceptWorkspaceMemberInviteCommand,
  AddAssigneeCommand,
  AddWorkspaceMemberCommand,
  CreateBacklogItemCommand,
  CreateIssueCommand,
  CreateProjectCommand,
  CreateTeamCommand,
  CreateWorkspaceCommand,
  FindBacklogItemsQuery,
  FindIssueQuery,
  FindIssuesQuery,
  FindProjectQuery,
  FindProjectsQuery,
  FindTeamsQuery,
  FindWorkspaceMemberQuery,
  FindWorkspacesQuery,
  MoveBacklogItemCommand,
  RemoveIssueCommand,
  RemoveWorkspaceMemberCommand,
  SendWorkspaceMemberInviteCommand,
  UpdateIssueCommand,
  UpdateWorkspaceMemberCommand,
} from './application/features';
import { UserCreatedReaction } from './application/reactions';
import {
  Backlog,
  BacklogItem,
  Issue,
  Project,
  Team,
  Workspace,
  WorkspaceMember,
  WorkspaceMemberInvite,
} from './domain/entities';
import {
  BacklogItemRepository,
  BacklogRepository,
  IssueRepository,
  ProjectRepository,
  TeamRepository,
  WorkspaceMemberInviteRepository,
  WorkspaceMemberRepository,
  WorkspaceRepository,
} from './infrastructure/repositories';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Workspace,
      WorkspaceMember,
      WorkspaceMemberInvite,
      Project,
      Team,
      Issue,
      Backlog,
      BacklogItem,
    ]),
    AuthModule,
  ],
  controllers: [
    WorkspaceController,
    WorkspaceMemberInviteController,
    ProjectController,
    IssueController,
    BacklogItemController,
  ],
  providers: [
    WorkspaceRepository,
    WorkspaceMemberRepository,
    WorkspaceMemberInviteRepository,
    ProjectRepository,
    TeamRepository,
    IssueRepository,
    BacklogRepository,
    BacklogItemRepository,
    FindWorkspacesQuery,
    CreateWorkspaceCommand,
    FindWorkspaceMemberQuery,
    AddWorkspaceMemberCommand,
    SendWorkspaceMemberInviteCommand,
    AcceptWorkspaceMemberInviteCommand,
    RemoveWorkspaceMemberCommand,
    UpdateWorkspaceMemberCommand,
    FindProjectsQuery,
    CreateProjectCommand,
    FindTeamsQuery,
    CreateTeamCommand,
    UserCreatedReaction,
    FindIssuesQuery,
    FindIssueQuery,
    CreateIssueCommand,
    UpdateIssueCommand,
    RemoveIssueCommand,
    AddAssigneeCommand,
    CreateBacklogItemCommand,
    FindBacklogItemsQuery,
    MoveBacklogItemCommand,
    FindProjectQuery,
  ],
  exports: [WorkspaceRepository],
})
export class WorkspaceModule {}
