steps:
- name: 'docker'
  args: ['buildx', 'create', '--driver', 'docker-container', '--name', 'container', '--use']
- name: 'docker'
  args: [ 'buildx', 'build', '--platform', 'linux/amd64,linux/arm64', '-t', 'us-east1-docker.pkg.dev/frenos-389613/openbao/openbao:$SHORT_SHA', '--push', '.', ]
