apiVersion: v1
kind: Secret
metadata:
  name: cloud-kms-secrets
type: Opaque
stringData:
  key.json: |
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-auth-delegator
subjects:
  - kind: ServiceAccount
    name: openbao-sa
    namespace: default

roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-secret-writer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-secret-writer-binding
subjects:
  - kind: ServiceAccount
    name: openbao-sa
roleRef:
  kind: Role
  name: openbao-secret-writer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: openbao
  labels:
    app: openbao
spec:
  ports:
    - port: 8200
      name: api
  selector:
    app: openbao
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao
spec:
  serviceName: openbao
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      serviceAccountName: openbao-sa
      containers:
        - name: openbao
          image: platform-openbao:3
          imagePullPolicy: IfNotPresent
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8200
              name: api
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: cloud-kms-secrets
              mountPath: /openbao/cloud-kms-secrets
            - name: openbao-data
              mountPath: /openbao/data
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: cloud-kms-secrets
          secret:
            secretName: cloud-kms-secrets
  volumeClaimTemplates:
    - metadata:
        name: openbao-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
