# API ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  NODE_ENV: "production"
  APP_URL: "http://epicstory.io/"
  API_PORT: "3000"
  DATABASE_USER: "postgres"
  DATABASE_HOST: "postgres"
  DATABASE_MIGRATION_HOST: "postgres"
  DATABASE_PORT: "5432"
  REDIS_URL: "redis://redis:6379"
  PASSWORD_ROUNDS: "10"
  JWT_EXPIRES_IN: "3600"
  GOOGLE_CALLBACK_URI: "http://epicstory.io/api/auth/google/callback"
  GOOGLE_APP_REDIRECT_URL: "http://epicstory.io/"
  DEFAULT_SENDER_EMAIL_ADDRESS: "noreply@example.com"
  EMAIL_SMTP_URL: "smtp://epicstory.io:587"
  EMAIL_SMTP_USER: "user"
---
# API Secrets ConfigMap (for sensitive data)
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-secrets
  labels:
    app: api
data:
  DATABASE_PASSWORD: "postgres"
  COOKIE_SECRET: "your-cookie-secret"
  JWT_SECRET: "your-jwt-secret"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  EMAIL_SMTP_PASSWORD: "password"
---
# App ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: frontend
data:
  API_URL: "http://epicstory.io/api"
  PEERJS_SERVER_HOST: "epicstory.io"
  PEERJS_SERVER_PATH: "/peerjs"
  PEERJS_SERVER_PORT: "3001"
  WEBSOCKET_URI: "/"
---
# PostgreSQL ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "epicstory"
  POSTGRES_USER: "postgres"
---
# PostgreSQL Secrets ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secrets
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: "postgres"
