# API ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  NODE_ENV: "production"
  APP_URL: "http://localhost:3000"
  API_PORT: "3000"
  DATABASE_USER: "postgres"
  DATABASE_HOST: "postgres"
  DATABASE_MIGRATION_HOST: "postgres"
  DATABASE_PORT: "5432"
  REDIS_URL: "redis://redis:6379"
  PASSWORD_ROUNDS: "10"
  JWT_EXPIRES_IN: "3600"
  GOOGLE_CALLBACK_URI: "http://localhost:3000/api/auth/google/callback"
  GOOGLE_APP_REDIRECT_URL: "http://localhost:8080"
  DEFAULT_SENDER_EMAIL_ADDRESS: "noreply@example.com"
  EMAIL_SMTP_URL: "smtp://localhost:587"
  EMAIL_SMTP_USER: "user"
---
# API Secrets ConfigMap (for sensitive data)
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-secrets
  labels:
    app: api
data:
  DATABASE_PASSWORD: "postgres"
  COOKIE_SECRET: "your-cookie-secret"
  JWT_SECRET: "your-jwt-secret"
  GOOGLE_CLIENT_ID: "your-google-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  EMAIL_SMTP_PASSWORD: "password"
---
# App ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: frontend
data:
  API_URL: "http://localhost:3000/api"
  PEERJS_SERVER_HOST: "localhost"
  PEERJS_SERVER_PORT: "3001"
  WEBSOCKET_URI: "/"
---
# PostgreSQL ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "epicstory"
  POSTGRES_USER: "postgres"
---
# PostgreSQL Secrets ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secrets
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: "postgres"
