apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epicstory-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: epicstory.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /peerjs
            pathType: Prefix
            backend:
              service:
                name: peerjs
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
