export {
  HiArrowNarrowLeft,
  HiSolidArrowNarrowLeft,
  HiSolidArrowSmLeft,
  FaSlackHash,
  HiClipboardList,
  OiPeople,
  BiPersonLinesFill,
  BiPeopleFill,
  BiPersonWorkspace,
  OiInbox,
  IoNotifications,
  MdSettingsRound,
  BiChevronExpand,
  BiChevronContract,
  OiSidebarExpand,
  OiSidebarCollapse,
  MdDraghandleRound,
  MdDragindicator,
} from "oh-vue-icons/icons";
