services:
  epicstory-postgres:
    image: postgres:14
    container_name: epicstory-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - epicstory-postgres:/var/lib/postgresql/data
    env_file:
      - .env
  epicstory-pgadmin:
    image: dpage/pgadmin4
    container_name: epicstory-pgadmin
    restart: always
    ports:
      - 3300:3300
    volumes:
      - epicstory-pgadmin:/var/lib/pgadmin
    env_file:
      - .env
  epicstory-peerjs:
    image: peerjs/peerjs-server
    command: peerjs -p 3001
    restart: always
    ports:
      - 3001:3001
  epicstory-redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
  epicstory-openbao:
    image: openbao/openbao:latest
    container_name: epicstory-openbao
    command: >
      sh -c "
        echo 'OpenBao container is ready for manual commands.' &&
        echo 'You can now exec into this container to start the server or run other commands.' &&
        echo 'To start a dev server: docker exec -it epicstory-openbao openbao server -dev -dev-listen-address=0.0.0.0:3002' &&
        echo 'Example to use CLI: docker exec -it epicstory-openbao vault --help' &&
        tail -f /dev/null
      "
    restart: always
    ports:
      - 3002:3002
    env_file:
      - .env
    volumes:
      - epicstory-openbao:/openbao
    tty: true
    stdin_open: true
volumes:
  epicstory-postgres:
    name: epicstory-postgres
  epicstory-pgadmin:
    name: epicstory-pgadmin
  epicstory-openbao:
    name: epicstory-openbao
